lavender_nursery/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_app.urls')),
]

my_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views 
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('',views.home, name='home'),
    path('services/',views.services , name='services'),
    # path('contact/',views.contact , name='contact'), #working progres
    # path('projects/',views.projects, name='projects'), #working progress 
    path('plants/',views.plant_catalog,name='plant_catalog'),
    path('plants/<int:plant_id>/',views.plant_detail,name='plant_detail'),
    path('plants/<int:plant_id>/request/', views.request_plant, name='request_plant'),
    path('checkout/', views.checkout, name='checkout'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('my-plant-requests/', views.my_plant_requests, name='my_plant_requests'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),
    path('services/', views.services, name='services'),
    path('services/<int:service_id>/', views.service_detail, name='service_detail'),
    path('request-quote/<int:service_id>/', views.request_quote, name='request_quote'),
    
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('manage-plants/', views.manage_plants, name='manage_plants'),
    path('add-plant/', views.add_plant, name='add_plant'),
    path('edit-plant/<int:plant_id>/', views.edit_plant, name='edit_plant'),
    path('delete-plant/<int:plant_id>/', views.delete_plant, name='delete_plant'),

    path('manage-services/', views.manage_services, name='manage_services'),
    path('add-service/', views.add_service, name='add_service'),
    path('edit-service/<int:service_id>/', views.edit_service, name='edit_service'),
    path('delete-service/<int:service_id>/', views.delete_service, name='delete_service'),

    path('respond-to-request/<str:request_type>/<int:request_id>/', views.respond_to_request, name='respond_to_request'),

    path('add-to-cart/<int:plant_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-cart/<int:item_id>/', views.update_cart, name='update_cart'),
]



#For development purposes
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now
from .utils import clean_phone_number 



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True)
    address = models.TextField(blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female')], blank=True)  

    def save(self, *args, **kwargs):
        if self.phone_number:
            try:
                self.phone_number = clean_phone_number(self.phone_number)
            except ValueError as e:
                raise ValueError(f"Error saving UserProfile: {e}")
        super().save(*args, **kwargs)

    def __str__(self):
        
        return f'{self.user.usernme}\'s Profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()



class Plant(models.Model):
    name = models.CharField(max_length=100)
    scientific_name = models.CharField(max_length=100)
    description = models.TextField()
    care_instructions = models.TextField()
    image = models.ImageField(upload_to='plants/', null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.IntegerField(default=0)
    

    def __str__(self):
        return self.name
    # to add care instruction in point form
    @property
    def care_instructions_list(self):
        return [instruction.strip() for instruction in self.care_instructions.split('\n') if instruction.strip()]

class PlantRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    request_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=[
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected')
    ], default='pending')
    delivery_address = models.TextField() 
    phone_number = models.CharField(max_length=15)  

    def __str__(self):
        return f"{self.user.username} - {self.plant.name} ({self.quantity})"


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='services/', null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2,default=30)
    duration_in_months = models.IntegerField(help_text="Duration in months", default=1)
    category = models.CharField(max_length=50,default='Landscaping', choices=[
        ('planting', 'Planting'),
        ('maintenance', 'Maintenance'),
        ('designing', 'Designing'),
        ('other', 'Other')
    ]      )
    location = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name



class QuoteRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_regex = RegexValidator(regex=r'^\+254\d{9}$', message="Phone number must be entered in the format: '+254 xxxxxxxxx'.")
    phone = models.CharField(validators=[phone_regex], max_length=13)
    property_image = models.ImageField(upload_to='property_images/', null=True, blank=True)
    location = models.CharField(max_length=100)
    additional_info = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=[
        ('pending', 'Pending'),
        ('In Progress', 'In progress'),
        ('Completed', 'Completed')
    ], default='pending')

    def save(self, *args, **kwargs):
        if self.phone:
            try:
                self.phone = clean_phone_number(self.phone)
            except ValueError as e:
                raise ValueError(f"Error saving QuoteRequest: {e}")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username} - {self.service.name}"

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    address = models.TextField() 
    phone = models.CharField(max_length=15)  
    email = models.EmailField()  
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity} x {self.plant.name} in Order {self.order.id}"



class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quantity} x {self.plant.name} in {self.user.username}'s cart"

    def total_price(self):
        return self.quantity * self.plant.price
    

my_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import UserProfile, PlantRequest, QuoteRequest
from .models import Plant, Service

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    gender = forms.ChoiceField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'gender']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone_number', 'address', 'profile_image']

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        # Phone validation logic here
        if phone_number:
            return phone_number
        return phone_number

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'  # Add form-control class for styling
            field.help_text = ''  # Disable help text display

class PlantRequestForm(forms.ModelForm):
    class Meta:
        model = PlantRequest
        fields = ['quantity', 'delivery_address', 'phone_number']
        widgets = {
            'delivery_address': forms.Textarea(attrs={'rows': 3}),
        }

class QuoteRequestForm(forms.ModelForm):
    class Meta:
        model = QuoteRequest
        fields = ['service', 'first_name', 'last_name', 'email', 'phone', 'property_image', 'location', 'additional_info']
        widgets = {
            'additional_info': forms.Textarea(attrs={'rows': 2}),
        }

class PlantForm(forms.ModelForm):
    class Meta:
        model = Plant
        fields = '__all__'

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'

my_app/templates/partials/features.html
{% extends 'base.html' %}
{% load static %}

<!-- Features Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 align-items-center">
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">
                <p class="fs-5 fw-bold text-primary">Why Choosing Us!</p>
                <h1 class="display-5 mb-4">Few Reasons Why People Choosing Us!</h1>
                <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                <a class="btn btn-primary py-3 px-4" href="">Explore More</a>
            </div>
            <div class="col-lg-6">
                <div class="row g-4 align-items-center">
                    <div class="col-md-6">
                        <div class="row g-4">
                            <div class="col-12 wow fadeIn" data-wow-delay="0.3s">
                                <div class="text-center rounded py-5 px-4" style="box-shadow: 0 0 45px rgba(0,0,0,.08);">
                                    <div class="btn-square bg-light rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                                        <i class="fa fa-check fa-3x text-primary"></i>
                                    </div>
                                    <h4 class="mb-0">100% Satisfaction</h4>
                                </div>
                            </div>
                            <div class="col-12 wow fadeIn" data-wow-delay="0.5s">
                                <div class="text-center rounded py-5 px-4" style="box-shadow: 0 0 45px rgba(0,0,0,.08);">
                                    <div class="btn-square bg-light rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                                        <i class="fa fa-users fa-3x text-primary"></i>
                                    </div>
                                    <h4 class="mb-0">Dedicated Team</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeIn" data-wow-delay="0.7s">
                        <div class="text-center rounded py-5 px-4" style="box-shadow: 0 0 45px rgba(0,0,0,.08);">
                            <div class="btn-square bg-light rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                                <i class="fa fa-tools fa-3x text-primary"></i>
                            </div>
                            <h4 class="mb-0">Modern Equipment</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

my_app/templates/partials/footer.html
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer mt-5 py-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-4">Our Office</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>muthangari road, Nairobi, KENYA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+254721727707</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@LavenderNursery.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-4">Services</h4>
                <a class="btn btn-link" href="{url 'services'}">Urban Gardening Solutions</a>
                <a class="btn btn-link" href="{url 'services'}">Lawn Installation and Maintenance</a>
                <a class="btn btn-link" href=""> Tree Pruning and Shaping</a>
                {% comment %} <a class="btn btn-link" href="">Garden Maintenance</a>
                <a class="btn btn-link" href="">Green Technology</a> {% endcomment %}
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-4">Quick Links</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Our Services</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
                <a class="btn btn-link" href="">Support</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-4">Newsletter</h4>
                <p>Get updates on upgrading your indoor / outdoor decor.</p>
                <div class="position-relative w-100">
                    <input class="form-control bg-light border-light w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

my_app/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0">
    <div class="d-flex align-items-center">
        <img src="{% static 'img/favicon.ico' %}" style="width: 40px; height: 40px; padding:5px" margin-right: 10px; alt="Logo">
        <h1 class="m-0"><span style="color: #663399;">Lavender</span> Nursery</h1>
    </div>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{% url 'home' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}">Home</a>
            <a href="{% url 'plant_catalog' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'plant_catalog' %}active{% endif %}">Plant Catalog</a>
            <a href="{% url 'services' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'services' %}active{% endif %}">Services</a>
        </div>
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_dashboard' %}">Admin</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profile' %}">My Profile</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'view_cart' %}" class="nav-item nav-link">
                            <i class="fas fa-shopping-cart"></i> Cart
                            <span class="badge bg-primary">{{ request.user.cartitem_set.count }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <form method="post" action="{% url 'logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link nav-link" style="text-decoration: none; color: inherit;">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

my_app/templates/partials/pageheader.html
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-5 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center py-5">
            <h1 class="display-3 text-white mb-4 animated slideInDown">Services</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Pages</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Services</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->